blog/urls.py
from . import views
from django.urls import path, include

app_name = "blog"

urlpatterns = [
    path('', views.ArticleList.as_view(), name='home'),
    path('page/<int:page>', views.ArticleList.as_view(), name='home'),
    path('article/<slug:slug>', views.ArticleDetail.as_view(), name='detail'),
    path('preview/<int:pk>', views.ArticlePreview.as_view(), name='preview'),
    path('category/<slug:slug>', views.CategoryList.as_view(), name='category'),
    path('category/<slug:slug>/page/<int:page>', views.CategoryList.as_view(), name='category'),   
    path('author/<slug:username>', views.AuthorList.as_view(), name='author'),
    path('author/<slug:username>/page/<int:page>', views.AuthorList.as_view(), name='author'),
    path('search/', views.SearchList.as_view(), name='search'),
    path('search/page/<int:page>', views.SearchList.as_view(), name='search'),
]

comment/api/urls.py
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns

from comment.api import views

urlpatterns = [
    path('comments/', views.CommentList.as_view(), name='comments-list'),
    path('comments/create/', views.CommentCreate.as_view(), name='comments-create'),
    path('comments/<int:pk>/', views.CommentDetail.as_view(), name='comment-detail'),
    path('comments/<int:pk>/react/<str:reaction>/', views.CommentDetailForReaction.as_view(), name='comments-react'),
    path('comments/<int:pk>/flag/', views.CommentDetailForFlag.as_view(), name='comments-flag'),
    path(
        'comments/<int:pk>/flag/state/change/',
        views.CommentDetailForFlagStateChange.as_view(),
        name='comments-flag-state-change'
    ),
    re_path(r'^comments/confirm/(?P<key>[^/]+)/$', views.ConfirmComment.as_view(), name='confirm-comment'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

comment/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

from comment import __version__
from comment.views import (
    CreateComment, UpdateComment, DeleteComment, SetReaction, SetFlag, ChangeFlagState,
    ConfirmComment)

app_name = 'comment'


urlpatterns = [
    path('create/', CreateComment.as_view(), name='create'),
    path('edit/<int:pk>/', UpdateComment.as_view(), name='edit'),
    path('delete/<int:pk>/', DeleteComment.as_view(), name='delete'),
    path('<int:pk>/react/<str:reaction>/', SetReaction.as_view(), name='react'),
    path('<int:pk>/flag/', SetFlag.as_view(), name='flag'),
    path('<int:pk>/flag/state/change/', ChangeFlagState.as_view(), name='flag-change-state'),
    re_path(r'^confirm/(?P<key>[^/]+)/$', ConfirmComment.as_view(), name='confirm-comment'),
    # javascript translations
    # The value returned by _get_version() must change when translations change.
    path(
        'jsi18n/',
        cache_page(86400, key_prefix='js18n-%s' % __version__)(JavaScriptCatalog.as_view()),
        name='javascript-catalog'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from account.views import Login, Register, activate
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/forms.py
from django import forms

from comment.models import Comment
from comment.conf import settings
from comment.messages import EmailInfo


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {'content': forms.Textarea(attrs={'rows': 1})}

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)
        if self.request.user.is_anonymous and settings.COMMENT_ALLOW_ANONYMOUS:
            self.fields['email'] = forms.EmailField(
                label=EmailInfo.LABEL,
                widget=forms.EmailInput(attrs={
                    'placeholder': EmailInfo.INPUT_PLACEHOLDER,
                    'title': EmailInfo.INPUT_TITLE
                    })
                )

    def clean_email(self):
        """this will only be executed when email field is present for unauthenticated users"""
        email = self.cleaned_data['email']
        return email.strip().lower()

comment/api/views.py
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from rest_framework import generics, permissions, status
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response
from rest_framework.views import APIView

from comment.validators import ValidatorMixin, ContentTypeValidator
from comment.api.serializers import CommentSerializer, CommentCreateSerializer
from comment.api.permissions import (
    IsOwnerOrReadOnly, FlagEnabledPermission, CanChangeFlaggedCommentState
)
from comment.models import Comment, Reaction, ReactionInstance, Flag, FlagInstance
from comment.utils import get_comment_from_key, CommentFailReason
from comment.messages import FlagError, EmailError


class CommentCreate(ValidatorMixin, generics.CreateAPIView):
    serializer_class = CommentCreateSerializer
    permission_classes = ()
    api = True

    def get_serializer_context(self):
        self.validate(self.request)
        context = super().get_serializer_context()
        context['user'] = self.request.user
        context['model_name'] = self.model_name
        context['app_name'] = self.app_name
        context['model_id'] = self.model_id
        context['parent_id'] = self.parent_id
        context['email'] = self.request.GET.get('email', None)
        return context


class CommentList(ContentTypeValidator, generics.ListAPIView):
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    api = True

    def get_queryset(self):
        self.validate(self.request)
        model_name = self.model_name
        pk = self.model_id
        content_type_model = ContentType.objects.get(model=model_name.lower())
        model_class = content_type_model.model_class()
        model_obj = model_class.objects.filter(id=pk).first()
        return Comment.objects.filter_parents_by_object(model_obj)


class CommentDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)


class CommentDetailForReaction(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['reaction_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs.get('pk'))
        reaction_type = kwargs.get('reaction', None)
        reaction_obj = Reaction.objects.get_reaction_object(comment)
        try:
            ReactionInstance.objects.set_reaction(
                user=request.user,
                reaction=reaction_obj,
                reaction_type=reaction_type
            )
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        comment.reaction.refresh_from_db()
        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlag(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, FlagEnabledPermission)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs.get('pk'))
        flag = Flag.objects.get_for_comment(comment)
        reason = request.data.get('reason') or request.POST.get('reason')
        info = request.data.get('info') or request.POST.get('info')
        try:
            FlagInstance.objects.set_flag(request.user, flag, reason=reason, info=info)
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlagStateChange(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (CanChangeFlaggedCommentState, )

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs.get('pk'))
        flag = Flag.objects.get_for_comment(comment)
        if not comment.is_flagged:
            return Response(
                {'detail': FlagError.REJECT_UNFLAGGED_COMMENT},
                status=status.HTTP_400_BAD_REQUEST
            )
        state = request.data.get('state') or request.POST.get('state')
        try:
            state = flag.get_clean_state(state)
            if not comment.is_edited and state == flag.RESOLVED:
                return Response(
                    {'detail': FlagError.RESOLVE_UNEDITED_COMMENT},
                    status=status.HTTP_400_BAD_REQUEST
                )
            flag.toggle_state(state, request.user)
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class ConfirmComment(APIView):
    @staticmethod
    def get(request, *args, **kwargs):
        key = kwargs.get('key', None)
        comment = get_comment_from_key(key)

        if comment.why_invalid == CommentFailReason.BAD:
            return Response({'detail': EmailError.BROKEN_VERIFICATION_LINK}, status=status.HTTP_400_BAD_REQUEST)

        if comment.why_invalid == CommentFailReason.EXISTS:
            return Response({'detail': EmailError.USED_VERIFICATION_LINK}, status=status.HTTP_200_OK)

        return Response(CommentSerializer(comment.obj).data, status=status.HTTP_201_CREATED)

comment/views/comments.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import FormView
from django.utils import timezone
from django.views import View
from django.contrib import messages
from django.core.mail import EmailMessage
from comment.models import Comment
from comment.forms import CommentForm
from comment.utils import (
    get_comment_context_data, get_model_obj, get_comment_from_key, process_anonymous_commenting,
    get_user_for_request, CommentFailReason
)
from comment.mixins import CanCreateMixin, CanEditMixin, CanDeleteMixin
from comment.conf import settings
from comment.messages import EmailError


class BaseCommentView(FormView):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(get_comment_context_data(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CreateComment(CanCreateMixin, BaseCommentView):
    comment = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment'] = self.comment
        return context

    def get_template_names(self):
        if self.request.user.is_anonymous or self.comment.is_parent:
            return ['comment/comments/base.html']
        else:
            return ['comment/comments/child_comment.html']

    def form_valid(self, form):
        app_name = self.app_name
        model_name = self.model_name
        model_id = self.model_id
        model_object = get_model_obj(app_name, model_name, model_id)
        parent_id = self.parent_id
        parent_comment = Comment.objects.get_parent_comment(parent_id)
        user = get_user_for_request(self.request)

        comment_content = form.cleaned_data['content']
        email = form.cleaned_data.get('email', None) or user.email
        time_posted = timezone.now()
        _comment = Comment(
            content_object=model_object,
            content=comment_content,
            user=user,
            parent=parent_comment,
            email=email,
            posted=time_posted
            )

        if settings.COMMENT_ALLOW_ANONYMOUS and not user:
            # send response, please verify your email to post this comment.
            response_msg = process_anonymous_commenting(self.request, _comment)
            messages.info(self.request, response_msg)
        else:
            _comment.save()
            self.comment = _comment
        
        current_site = get_current_site(self.request)
        article = self.comment.content_object
        author_email = article.author.email
        user_email = self.comment.user.email
        if author_email == user_email :
            author_email = False
            user_email = False
        parent_email = False
        if self.comment.parent :
            parent_email = self.comment.parent.user.email
            if parent_email in [author_email, user_email] :
                parent_email = False

        if author_email :
            email = EmailMessage (
                "دیدگاه جدید",
                "دیدگاه جدیدی برای مقاله «{}» که شما نویسنده آن هستید، ارسال شده است : \n {} {}".format(article, current_site, reverse('blog:detail', kwargs={'slug': article.slug})),
                to=[author_email]
            )
            email.send()

        if user_email :
            email = EmailMessage (
                "دیدگاه شما دریافت شد",
                "دیدگاه شما دریافت شد و به زودی به آن پاسخ می‌دهیم.",
                to=[user_email]
            )
            email.send()

        if parent_email :
            email = EmailMessage (
                "پاسخ به دیدگاه شما",
                "پاسخی به دیدگاه شما در مقاله «{}» ثبت شده است،برای مشاهده روی لینک زیر کلیک کنید : \n {} {}".format(article, current_site, reverse('blog:detail', kwargs={'slug': article.slug})),
                to=[parent_email]
            )
            email.send()

        return self.render_to_response(self.get_context_data())


class UpdateComment(CanEditMixin, BaseCommentView):
    comment = None

    def get_object(self):
        self.comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        return self.comment

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context['comment_form'] = CommentForm(instance=self.comment, request=self.request)
        context['comment'] = self.comment
        return render(request, 'comment/comments/update_comment.html', context)

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST, instance=self.comment, request=self.request)
        context = self.get_context_data()
        if form.is_valid():
            form.save()
            context['comment'] = self.comment
            return render(request, 'comment/comments/comment_content.html', context)


class DeleteComment(CanDeleteMixin, BaseCommentView):
    comment = None

    def get_object(self):
        self.comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        return self.comment

    def get(self, request, *args, **kwargs):
        data = dict()
        context = self.get_context_data()
        context["comment"] = self.comment
        context['has_parent'] = not self.comment.is_parent
        data['html_form'] = render_to_string('comment/comments/comment_modal.html', context, request=request)
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        self.comment.delete()
        context = self.get_context_data()
        return render(request, 'comment/comments/base.html', context)


class ConfirmComment(View):
    @staticmethod
    def get(request, *args, **kwargs):
        key = kwargs.get('key', None)
        comment = get_comment_from_key(key)

        if comment.why_invalid == CommentFailReason.BAD:
            messages.error(request, EmailError.BROKEN_VERIFICATION_LINK)
        elif comment.why_invalid == CommentFailReason.EXISTS:
            messages.warning(request, EmailError.USED_VERIFICATION_LINK)

        if not comment.is_valid:
            return render(request, template_name='comment/anonymous/discarded.html')

        return redirect(comment.obj.get_url(request))

comment/templates/comment/comments/apply_icon.html
<button class="{% block apply_btn_cls %}btn btn-link{% endblock apply_btn_cls %}" type="submit" name="form_type">
{% block apply_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
        fill="none" stroke="{% block apply_icon_color %}#00bc8c{% endblock apply_icon_color %}" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round" class="feather feather-check">
    <polyline points="20 6 9 17 4 12"></polyline>
</svg>
{% endblock apply_img_icon %}
</button>

comment/templates/comment/comments/cancel_icon.html
<a class="js-comment-cancel {% block cancel_btn_cls %}btn btn-link{% endblock cancel_btn_cls %}" href="#">
{% block cancel_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block cancel_icon_color %}#E74C3C{% endblock cancel_icon_color %}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
    <line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line>
</svg>
{% endblock cancel_img_icon %}
</a>

comment/templates/comment/comments/comment_body.html
{% load comment_tags %}
<div class="row">
    {% if has_valid_profile %}
        <div class="{% block image_wrapper_cls %}col-2 col-md-1{% endblock image_wrapper_cls %}">
            <a href="{% get_profile_url comment %}">
                <img class="{% block image_cls %}w-100{% endblock image_cls %}"
                     src="{% get_img_path comment %}" alt="{% get_username_for_comment comment %}">
            </a>
        </div>
    {% endif %}
    {% include 'comment/comments/comment_content.html' with comment=comment %}
    {% if allowed_flags and comment.user != user %}
        <div class="col-1">
            {% include "comment/flags/flags.html" %}
        </div>
    {% endif %}
</div>

comment/templates/comment/comments/comment_content.html
{% load comment_tags %}
{% load i18n %}


<div class="media-comment-bubble left-top js-updated-comment {% if comment.has_flagged_state %}flagged-comment {% endif %}{% block content_wrapper_cls %}{% if has_valid_profile %}col-9 col-md-10{% else %}co-11 mx-3{% endif %}{% endblock content_wrapper_cls %}" id="{{ comment.urlhash }}">
    {% block comment_content %}
    {% render_content comment 30 %}
    {% endblock comment_content %}
    <div class="blockquote-footer">
        <small>
            {% get_profile_url comment as profile_url %}
            <{% if comment.user %}a{% else %}span{% endif %}
                class="{% block username_cls %}{% endblock username_cls %}" {% if profile_url %}href="{{ profile_url }}"{% endif %}
                title="{% if comment.user %}{% blocktrans %}view {{ comment.user }} profile{% endblocktrans %}{% else %}{% trans 'comment by anonymous user' %}{% endif %}"
            >
                {{comment.user.get_full_name }}
            </{% if comment.user %}a{% else %}span{% endif %}><br>
            {% if comment.is_edited %}
            <span class="font-italic" title="{% trans 'Edited' %}">{% blocktrans with edited_time=comment.edited|timesince %}ویرایش شده: {{ edited_time }} قبل{% endblocktrans %}</span>
            {% else %}
            <span class="font-italic" title="{% trans 'Posted' %}">{% blocktrans with posted_time=comment.posted|timesince %}{{ posted_time }} قبل{% endblocktrans %}</span>
            {% endif %}
            {% can_delete_comment comment user as can_delete %}
            {% if comment.user == user %}
                | {% include 'comment/comments/edit_icon.html' %}
                {% include 'comment/comments/delete_icon.html' %}
            {% elif can_delete %}
                | {% include 'comment/comments/delete_icon.html' %}
                {% if comment.is_flagged %}
                    {% include 'comment/comments/reject_icon.html' %}
                    {% if comment.is_edited %}
                        {% include 'comment/comments/resolve_icon.html' %}
                    {% endif %}
                {% endif %}
            {% endif %}
            {% if comment.is_parent %}
                {% get_replies_count comment user as reply_count %}
                | <span class="js-reply-number text-dark">{{ reply_count }}</span>
                <a class="js-reply-link {% block reply_link_cls %}btn btn-link ml-1{% endblock reply_link_cls %}" href="#">
                    پاسخ
                </a>
            {% endif %}
        </small>
        {% include "comment/reactions/reactions.html" with comment=comment %}
    </div>
</div>

comment/templates/comment/comments/comment_form.html
{% load comment_tags %}
{% if comment_form.non_field_errors %}
    <div class='alert alert-danger' role='alert'>
        {% for error in comment_form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}
{% for field in comment_form.visible_fields %}
    {% if field.field.label == 'Content' %}
    {% render_field field placeholder=placeholder class='js-comment-input form-control form-control-sm rounded-0' %}
    {% else %}
    {% render_field field class='js-comment-input form-control form-control-sm rounded-0' %}
    {% endif %}
{% endfor %}

comment/templates/comment/comments/create_comment.html
{% load comment_tags %}
{% load i18n %}
{% if is_anonymous_allowed or user.is_authenticated %}
    <form class="js-comment-form" method="post" data-url="{% url 'comment:create' %}">
        {% csrf_token %}
        <div class="row">
            <div class="{% block text_area_wrapper_cls %}col-sm-9 col-md-10 px-2 m-2 m-sm-0{% endblock text_area_wrapper_cls %}">
                {% include 'comment/comments/comment_form.html' with placeholder=placeholder %}
            </div>
            <input name="model_name" value="{% get_model_name model_object %}" hidden>
            <input name="model_id" value="{{ model_object.id }}" hidden>
            <input name="app_name" value="{% get_app_name model_object %}" hidden>
            <input name="oauth" value="{{oauth}}" hidden>
            {% if comment %}
            <input name="parent_id" value="{{ comment.id }}" type="hidden"/>
            {% endif %}
            <div class="{% block submit_button_wrapper_cls %}col-sm-3 col-md-2 px-2 m-3 m-sm-0{% endblock submit_button_wrapper_cls %}">
                <button disabled class="js-comment-btn {% block submit_button_cls %}btn btn-outline-success btn-block btn-sm{% endblock submit_button_cls %}"
                        type="submit" name="form_type" value="{% if comment %}child{% else %}parent{% endif %}">
                    {% if comment %}{% trans "پاسخ" %}{% else %}{% trans "ارسال" %}{% endif %}
                </button>
            </div>
        </div>
    </form>
{% endif %}
{% if user.is_anonymous %}
    <div class="d-flex mb-3">
        {% if is_anonymous_allowed %}
            <p class="text-muted {% if comment %}h7 my-auto {% endif %}">{% trans "Comment Anonymously or" %}
            <a class="text-success {% if comment %}h7 my-auto {% endif %}" href="{{login_url}}?next={{request.path}}">
                {% trans "Login" %}
            </a>
            {% trans "to keep your conversations intact" %}</p>
        {% else %}
            <p class="text-muted">
                {% trans "ارسال دیدگاه : " %}
                <a class="text-success {% if comment %}h7 my-auto {% endif %}" href="{{login_url}}?next={{request.path}}">
                    {% trans "ورود" %}
                </a>
            </p>
        {% endif %}
        {% if oauth %}
            {% block oauth %}
            <a class="mx-1 my-0 h4 github-color" href="{% url 'social:begin' 'github' %}?next={{request.path}}"><i class="fa fa-github-square"></i></a>
            <a class="mx-1 my-0 h4 facebook-color" href="{% url 'social:begin' 'facebook' %}?next={{request.path}}"><i class="fa fa-facebook-square"></i></a>
            <a class="mx-1 my-0 h4 twitter-color" href="{% url 'social:begin' 'twitter' %}?next={{request.path}}"><i class="fa fa-twitter-square"></i></a>
            <a class="mx-1 my-0 h4 google-color" href="{% url 'social:begin' 'google-oauth2' %}?next={{request.path}}"><i class="fa fa-google-plus-square"></i></a>
            {% endblock oauth %}
        {% endif %}
    </div>
{% endif %}

comment/templates/comment/comments/edit_icon.html
{% load comment_tags %}
{% load i18n %}
<a title='{% trans "Edit comment" %}' class="js-comment-edit {% block edit_link_cls %}btn btn-link{% endblock edit_link_cls %}"
   href="{% url 'comment:edit' pk=comment.id %}?model_name={% get_model_name model_object %}&model_id={{ model_object.id }}&app_name={% get_app_name model_object %}&oauth={{oauth}}">
{% block edit_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none"
     stroke="{% block edit_icon_color %}#00bc8c{% endblock edit_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit">
    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
</svg>
{% endblock edit_img_icon %}
</a>

comment/templates/comment/comments/resolve_icon.html
{% load comment_tags %}
{% load i18n %}
<button title="{% if comment.has_resolved_state %}{% trans "Flag resolved" %}{% else %}{% trans "Resolve the flag" %}{% endif %}" class="js-flag-resolve {% block resolved_btn_cls %}btn btn-link{% endblock resolved_btn_cls %}" data-state="{{ comment.flag.RESOLVED }}" data-url="{% url 'comment:flag-change-state' pk=comment.id %}">

{% block resolved_img_icon %}
<svg class="{% if comment.has_resolved_state %}flag-resolved{% endif %}"
     xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block resolved_icon_color %}#E74C3C{% endblock resolved_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
     <path d="m11.939 20.395c-2.3228-3.8704-6.6445-2.2732-10.044-1.5539l0.10519-15.842h6c1.9144 0.42177 3.3887 1.4863 3.9187 3.1939"></path>
     <path d="m7.2106 9.7002 3.6287 5.1401 8.115-13.216" stroke-width="2.5"></path>
     <path d="m11.939 20.395c2.3228-3.8704 6.6445-2.2732 10.044-1.5539l-0.10519-15.841"></path>
</svg>
{% endblock resolved_img_icon %}
</button>

comment/templates/comment/comments/update_comment.html
{% load comment_tags %}
<div class="js-comment-update-mode col-10 col-md-11">
    <form class="js-comment-edit-form" method="post" data-url="{% url 'comment:edit' pk=comment.id %}">
        {% csrf_token %}
        {% include 'comment/comments/comment_form.html' with placeholder=placeholder %}
        <footer class="blockquote-footer edit-comment mt-2">
            <small>
                <input name="model_name" value="{% get_model_name model_object %}" hidden>
                <input name="model_id" value="{{ model_object.id }}" hidden>
                <input name="app_name" value="{% get_app_name model_object %}" hidden>
                <input name="oauth" value="{{oauth}}" hidden>

                {% include 'comment/comments/apply_icon.html' %}
                {% include 'comment/comments/cancel_icon.html' %}
            </small>
        </footer>
    </form>
</div>