blog/urls.py
from . import views
from django.urls import path, include

app_name = "blog"

urlpatterns = [
    path('', views.ArticleList.as_view(), name='home'),
    path('page/<int:page>', views.ArticleList.as_view(), name='home'),
    path('article/<slug:slug>', views.ArticleDetail.as_view(), name='detail'),
    path('preview/<int:pk>', views.ArticlePreview.as_view(), name='preview'),
    path('category/<slug:slug>', views.CategoryList.as_view(), name='category'),
    path('category/<slug:slug>/page/<int:page>', views.CategoryList.as_view(), name='category'),   
    path('author/<slug:username>', views.AuthorList.as_view(), name='author'),
    path('author/<slug:username>/page/<int:page>', views.AuthorList.as_view(), name='author'),
    path('search/', views.SearchList.as_view(), name='search'),
    path('search/page/<int:page>', views.SearchList.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from account.views import Login, Register, activate
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils import timezone
from comment.models import Comment
from django.utils.html import format_html
from extensions.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation

# My managers
#Set the class as objects in related model. --> objects = ArticleManager()
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField (verbose_name="آدرس آی‌پی")


# Create your models here.
class Category(models.Model):
    parent = models.ForeignKey('self', default=None,blank=True,null=True,on_delete=models.SET_NULL,related_name='children', verbose_name='زیردسته')
    title = models.CharField(max_length=200, verbose_name = "عنوان دسته بندی")
    slug = models.SlugField(max_length=100, unique=True, verbose_name = "آدرس دسته بندی")
    status = models.BooleanField(default=True ,verbose_name = "آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")
    
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title
    
    objects = CategoryManager()



class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
        ('i', 'در حال بررسی'),
        ('b', 'عدم تایید'),
    )

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='نویسنده')
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name='articles')
    title = models.CharField(max_length=200, verbose_name = "عنوان مقاله")
    slug = models.SlugField(max_length=100, unique=True, verbose_name = "آدرس مقاله")
    description = models.TextField(verbose_name = "توضیحات مقاله")
    thumbnail = models.ImageField(upload_to="images", verbose_name = "تصویر مقاله")
    publish = models.DateTimeField(default=timezone.now, verbose_name = "زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name = "وضعیت")
    is_special = models.BooleanField(default=False ,verbose_name = "مقاله ویژه")
    # the field name should be comments
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through="ArticleHit", blank=True, related_name="hits", verbose_name = "بازدید ها")


    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:home")
    
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"

    def thumbnail_tag(self):
        return format_html( "<img width=100 height=75 style='border-radius:5px;' src='{}'>".format(self.thumbnail.url) )
    thumbnail_tag.short_description = "تصویر"

    def category_to_str(self):
        return "، ".join([category.title for category in self.category.active()])
    category_to_str.short_description = "دسته بندی"

    objects = ArticleManager()


class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.core.paginator import Paginator
from account.models import User
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from django.views.generic import  ListView, DetailView
from account.mixins import AuthorAccessMixin
from django.db.models import Q
# Create your views here.
# def home(request, page=1):
#     articles_list = Article.objects.published()
#     paginator = Paginator(articles_list,5)
#     articles = paginator.get_page(page)
#     context = {
#         'articles' : articles,
#     }
#     return render(request, 'blog/home.html', context)

class ArticleList(ListView):
    queryset = Article.objects.published()
    paginate_by = 4
    
    # context_object_name = "articles"
    # template_name = "blog/home.html"

# def detail(request, slug):
#     article = get_object_or_404(Article.objects.published(), slug=slug)
#     context = {
#         'article' : article,
#     }
#     return render(request, 'blog/detail.html', context)

class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)
        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all() : 
            article.hits.add(ip_address)
        
        return article


class ArticlePreview(AuthorAccessMixin ,DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)


# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     articles_list = category.articles.published()
#     paginator = Paginator(articles_list,5)
#     articles = paginator.get_page(page)
#     context = {
#         'category' : category,
#         'articles' : articles,
#     }
#     return render(request, 'blog/category.html', context)

class CategoryList(ListView):
    paginate_by = 4
    template_name = "blog/category_list.html"

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 4
    template_name = "blog/author_list.html"

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context
        


class SearchList(ListView):
    paginate_by = 1
    template_name = "blog/search_list.html"

    def get_queryset(self):
        search = self.request.GET.get('q')
        return Article.objects.filter( Q(description__icontains=search) | Q(title__icontains=search) )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}درباره ما{% endblock title %}

{% block content %}
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% load comment_tags %}
{% load humanize %}
{% load base_tags %}


{% block custom_css %} 
<link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">
{% endblock %}


{% block title %} {{ object.title }} {% endblock title %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{ object.title }}</h1>
            {{ object.publish | naturaltime }}
            {% if article.is_special %}
              <p><span class="badge badge-danger" style="font-size:30px;">ویژه</span></p>
            {% endif %}
            <div>
              {% ratings object %}
            </div>
            <div>
              تعداد بازدید ها : {{object.hits.count}}
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

 <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-justify">
          <aside>
            {% popular_articles %}
            {% hot_articles %}
          </aside>
          {% if object.is_special %}
            {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
              {{object.description|safe}}
            {% else %}
              {{article.description|striptags|truncatewords:35}}
              <p class="alert alert-warning text-center">این یک مقاله ویژه می‌باشد! برای مشاهده آن، باید <a class="alert-link" href="#" style="color: dodgerblue;"> اشتراک ویژه </a>تهیه کنید.</p>
            {% endif %}
          {% else %}
            {{object.description|safe}}
          {% endif %}
          {% render_comments object request %}
          {% include_bootstrap %}
          {% include_static %}
        </div>
      </div>
    </div>
  </article>
{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}
    
{% endblock %}


{% block previous_page_url %} {% url 'blog:home'  page_obj.previous_page_number %} {% endblock %}
{% block next_page_url %} {% url 'blog:home'  page_obj.next_page_number %} {% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center">نویسنده : {{ author.get_full_name }}</h3> 
{% endblock %}

{% block previous_page_url %} {% url 'blog:author' author.username page_obj.previous_page_number %} {% endblock %}
{% block next_page_url %} {% url 'blog:author' author.username page_obj.next_page_number %} {% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>سیلیسیم | {% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/clean-blog.css' %}" rel="stylesheet">
  <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
  {% block custom_css %} {% endblock %}
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      {% category_navbar %}
    </div>
  </nav>

{% block content %}

{% endblock %}

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>


  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center">دسته بندی : {{ category.title }}</h3> 
{% endblock %}

{% block previous_page_url %} {% url 'blog:category' category.slug page_obj.previous_page_number %} {% endblock %}
{% block next_page_url %} {% url 'blog:category' category.slug page_obj.next_page_number %} {% endblock %}

templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}تماس با ما{% endblock title %}

{% block content %}
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}


{% block custom_css %} 
<link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}دسته بندی{% endblock title %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url( {% static 'blog/img/home-bg.jpg' %} )">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>سیلیسیم</h1>
          </div>
        </div>
      </div>
    </div>
  </header>


  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% block header %}{% endblock %}
        <aside>
          {% popular_articles %}
          {% hot_articles %}
        </aside>
        {% for article in object_list %}
          <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
              {{article.title}}
              {% if article.is_special %}
                <span class="badge badge-danger" style="font-size:15px;">ویژه</span>
              {% endif %}
              </h2>
              <div>{% ratings article %}</div>
              <h3 class="post-subtitle">
                {{article.description|striptags|truncatewords:25}}
              </h3>
            </a>
            <p class="post-meta">نوشته شده توسط
              <a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name }}</a>
              در {{ article.publish | naturaltime }}</p>
              <div>
                {% for cat in article.category.active %}
                  <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }}</a>
                {% endfor %}
              </div>
              <div>
                تعداد بازدید ها : {{article.hits.count}}
              </div>
              <hr>
        </div>
        {% empty %}
          <p class="alert alert-warning text-center">متاسفانه محتوایی برای نمایش یافت نشد.</p>
        {% endfor %}
        <!-- Pager -->
        {% if is_paginated %}
        <div class="clearfix pager-button">
            {% if page_obj.has_previous %}
              <a class="btn btn-primary float-right ml-3" href="{% block previous_page_url %}{% endblock %}">&rarr; پست های جدید </a>
            {% endif %}
            {% if page_obj.has_next %}
              <a class="btn btn-primary float-right" href="{% block next_page_url %}{% endblock %}">پست های قدیمی &larr;</a>
            {% endif %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

templates/blog/search_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center">جستجو : {{ search }}</h3> 
{% endblock %}

{% block previous_page_url %} {% url 'blog:search' page_obj.previous_page_number %}?q={{ search }}
{% endblock %}
{% block next_page_url %} {% url 'blog:search' page_obj.next_page_number %}?q={{ search }}
{% endblock %}